### ISSUE TITLE
fix fails to save new question on deploys

### ISSUE THREAD

**Issue by Bilalm354** [haffi96/quiz-app#73]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/53113053/217977965-611a9641-55c9-4bff-afa2-28c120e8f7e7.png">

**Comment by haffi96** [comment]
fck i know the problem, when you manually add data to postgres, i think it doesn't auto update pkey columns

**Comment by haffi96** [comment]
Fixed by https://github.com/haffi96/quiz-app/commit/97d523eafcde714958af9b04014fd588af598306

<img width="544" alt="image" src="https://user-images.githubusercontent.com/53666594/218209165-51e0d876-a9e5-47e3-8f1b-8181c0a58184.png">

![image](https://user-images.githubusercontent.com/53666594/218209192-37baf03d-b4a9-4b29-82cb-49289cd46dd9.png)
